//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CG.Access.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItemShift
    {
        public long Id { get; set; }
        public long MenuItemId { get; set; }
        public Nullable<long> ShiftId { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual MenuItem MenuItem { get; set; }
        public virtual Shift Shift { get; set; }
    }
}
