//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CG.Access.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public MenuItem()
        {
            this.MenuItemShifts = new HashSet<MenuItemShift>();
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime UpdatedDateTime { get; set; }
        public long UpdatedBy { get; set; }
        public long CategoryId { get; set; }
    
        public virtual MenuItemCategory MenuItemCategory { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<MenuItemShift> MenuItemShifts { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}
