//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CG.Access.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Province
    {
        public Province()
        {
            this.Restaurants = new HashSet<Restaurant>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public long CountryId { get; set; }
        public string Code { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<Restaurant> Restaurants { get; set; }
    }
}
