//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CG.Access.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public Restaurant()
        {
            this.MenuItemCategories = new HashSet<MenuItemCategory>();
            this.Orders = new HashSet<Order>();
            this.ShiftTypes = new HashSet<ShiftType>();
            this.Taxes = new HashSet<Tax>();
            this.Terminals = new HashSet<Terminal>();
            this.Users = new HashSet<User>();
            this.Tables = new HashSet<Table>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string ZipCode { get; set; }
        public string Fax { get; set; }
        public string ContactPerson { get; set; }
        public Nullable<long> ProvinceId { get; set; }
        public string LandLineNumber { get; set; }
        public string Mobile { get; set; }
    
        public virtual ICollection<MenuItemCategory> MenuItemCategories { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Province Province { get; set; }
        public virtual ICollection<ShiftType> ShiftTypes { get; set; }
        public virtual ICollection<Tax> Taxes { get; set; }
        public virtual ICollection<Terminal> Terminals { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Table> Tables { get; set; }
    }
}
