//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CG.Access.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift
    {
        public Shift()
        {
            this.MenuItemShifts = new HashSet<MenuItemShift>();
        }
    
        public long Id { get; set; }
        public long ShiftTypeId { get; set; }
    
        public virtual ICollection<MenuItemShift> MenuItemShifts { get; set; }
        public virtual ShiftType ShiftType { get; set; }
    }
}
