//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CG.Access.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftType
    {
        public ShiftType()
        {
            this.Shifts = new HashSet<Shift>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public long RestaurantId { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
        public virtual ICollection<Shift> Shifts { get; set; }
    }
}
