//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CG.Access.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public Table()
        {
            this.TableMeals = new HashSet<TableMeal>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public long TableStatusId { get; set; }
        public int Seats { get; set; }
        public int MaxSeats { get; set; }
        public bool IsAvailable { get; set; }
        public long RestaurantId { get; set; }
    
        public virtual TableStatu TableStatu { get; set; }
        public virtual ICollection<TableMeal> TableMeals { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
