//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CG.Access.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableMeal
    {
        public TableMeal()
        {
            this.Transactions = new HashSet<Transaction>();
            this.Orders = new HashSet<Order>();
        }
    
        public long Id { get; set; }
        public long TableId { get; set; }
        public long TableMealStatusId { get; set; }
        public Nullable<System.DateTime> StartedTime { get; set; }
        public Nullable<System.DateTime> EndedTime { get; set; }
        public Nullable<int> NumberOfPeople { get; set; }
        public long UpdatedBy { get; set; }
        public System.DateTime UpdatedDateTime { get; set; }
    
        public virtual Table Table { get; set; }
        public virtual TableMealStatu TableMealStatu { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
