//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CG.Access.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableMeal
    {
        public TableMeal()
        {
            this.TableMealOrders = new HashSet<TableMealOrder>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public long Id { get; set; }
        public long TableId { get; set; }
        public long TableStatusId { get; set; }
        public Nullable<System.DateTime> StartedTime { get; set; }
        public Nullable<System.DateTime> EndedTime { get; set; }
        public Nullable<int> NumberOfPeople { get; set; }
    
        public virtual Table Table { get; set; }
        public virtual TableStatu TableStatu { get; set; }
        public virtual ICollection<TableMealOrder> TableMealOrders { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
