//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CG.Access.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public long Id { get; set; }
        public long TableMealId { get; set; }
        public long PaymentTypeId { get; set; }
        public Nullable<System.DateTime> TransactionTime { get; set; }
        public Nullable<decimal> AggregateAmountWithoutTax { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Tip { get; set; }
        public Nullable<long> TerminalId { get; set; }
        public string Note { get; set; }
        public System.DateTime UpdatedDateTime { get; set; }
        public long UpdatedBy { get; set; }
    
        public virtual PaymentType PaymentType { get; set; }
        public virtual TableMeal TableMeal { get; set; }
        public virtual Terminal Terminal { get; set; }
        public virtual User User { get; set; }
    }
}
