CREATE TABLE [dbo].[CR_ACCOUNT_TABLE] (
    [TABLE_ID]   INT      NOT NULL,
    [ACCOUNT_ID] INT      NOT NULL,
    [CAPACITY]   INT      NOT NULL,
    [ENABLED]    SMALLINT NULL,
    [BOOKED]     SMALLINT NOT NULL,
    CONSTRAINT [PK_CR_ACCOUNT_TABLE] PRIMARY KEY CLUSTERED ([TABLE_ID] ASC, [ACCOUNT_ID] ASC)
);

