CREATE TABLE [dbo].[CR_ACCOUNT_LEVEL_TYPES] (
    [ACCOUNT_LEVEL_ID] INT        NOT NULL,
    [NAME]             NCHAR (60) NOT NULL,
    [MODIFIED_TIME]    ROWVERSION NOT NULL,
    [MODIFIED_BY]      INT        NULL,
    CONSTRAINT [PK_CR_ACCOUNT_LEVEL_TYPES] PRIMARY KEY CLUSTERED ([ACCOUNT_LEVEL_ID] ASC)
);

