CREATE TABLE [dbo].[CR_ACCOUNT_LEVEL] (
    [ACCOUNT_ID]       INT        NOT NULL,
    [ACCOUNT_LEVEL_ID] INT        NOT NULL,
    [MODIFIED_TIME]    ROWVERSION NULL,
    [MODIFIED_BY]      INT        NULL,
    CONSTRAINT [PK_CR_ACCOUNT_LEVEL] PRIMARY KEY CLUSTERED ([ACCOUNT_ID] ASC, [ACCOUNT_LEVEL_ID] ASC)
);

