CREATE TABLE [dbo].[CR_MENU_MODIFIER_GROUP] (
    [MODIFIER_GROUP_ID] INT         NOT NULL,
    [ACCOUNT_ID]        INT         NOT NULL,
    [NAME]              NCHAR (100) NOT NULL,
    [ENABLED]           SMALLINT    NULL,
    [EXCLUSIVED]        SMALLINT    NULL,
    [REQUIRED]          SMALLINT    NULL,
    [MODIFIED_TIME]     ROWVERSION  NULL,
    [MODIFIED_BY]       INT         NOT NULL,
    CONSTRAINT [PK_CR_MENU_MODIFIER_GROUP] PRIMARY KEY CLUSTERED ([MODIFIER_GROUP_ID] ASC)
);

