CREATE TABLE [dbo].[CR_PRINTER_CONFIG] (
    [PRINTER_ID]    INT         IDENTITY (1, 1) NOT NULL,
    [ACCOUNT_ID]    INT         NULL,
    [NAME]          NCHAR (100) NULL,
    [TYPE]          INT         NULL,
    [MODIFIED_TIME] ROWVERSION  NULL,
    [MODIFIED_BY]   INT         NOT NULL,
    CONSTRAINT [PK_CR_PRINTER_CONFIG] PRIMARY KEY CLUSTERED ([PRINTER_ID] ASC)
);

