CREATE TABLE [dbo].[CR_RESTO_PAYMENT_MOTHOD] (
    [METHOD_ID]  INT      NOT NULL,
    [ACCOUNT_ID] INT      NOT NULL,
    [ENABLED]    SMALLINT NOT NULL,
    CONSTRAINT [PK_CR_RESTO_PAYMENT_MOTHOD] PRIMARY KEY CLUSTERED ([METHOD_ID] ASC)
);

