CREATE TABLE [dbo].[RC_ACCOUNT_TABLE] (
    [TABLE_ID]   BIGINT      NOT NULL,
    [ACCOUNT_ID] BIGINT      NOT NULL,
    [CAPACITY]   INT         NULL,
    [ENABLED]    SMALLINT NULL,
    [BOOKED]     SMALLINT NOT NULL,
    CONSTRAINT [PK_RC_ACCOUNT_TABLE] PRIMARY KEY CLUSTERED ([TABLE_ID] ASC, [ACCOUNT_ID] ASC),
	CONSTRAINT [FK_RC_ACCOUNT_TABLE_RC_ACCOUNTS] FOREIGN KEY ([ACCOUNT_ID]) REFERENCES [dbo].[RC_ACCOUNTS] ([ACCOUNT_ID]),
);
