CREATE TABLE [dbo].[RC_ACCOUNTS] (
    [ACCOUNT_ID]    BIGINT IDENTITY (1, 1) NOT NULL,
    [EMAIL]         NCHAR (60)    NOT NULL,
    [PASSWORD]      NVARCHAR (50) NOT NULL,
    [MODIFIED_TIME] ROWVERSION    NOT NULL,
    [ACTIVATION]    NCHAR (32)    NOT NULL,
    [ENABLED]       SMALLINT      NOT NULL,
    [CREATED_TIME]  DATETIME2 (7) NOT NULL,
	[ACCOUNT_LEVEL] INT NOT NULL,
    CONSTRAINT [PK_RC_ACCOUNTS] PRIMARY KEY CLUSTERED ([ACCOUNT_ID] ASC)
);