CREATE TABLE [dbo].[RC_ACCOUNTS] (
    [ACCOUNT_ID]    INT           IDENTITY (1, 1) NOT NULL,
    [EMAIL]         NCHAR (60)    NULL,
    [PASSWORD]      NVARCHAR (50) NULL,
    [MODIFIED_TIME] ROWVERSION    NULL,
    [ACTIVATION]    NCHAR (32)    NOT NULL,
    [ENABLED]       SMALLINT      NULL,
    [CREATED_TIME]  DATETIME2 (7) NULL,
    CONSTRAINT [PK_RC_ACCOUNTS] PRIMARY KEY CLUSTERED ([ACCOUNT_ID] ASC)
);

