CREATE TABLE [dbo].[RC_ACTION_HISTORY] (
    [ID]          INT         NOT NULL,
    [ACCOUNT_ID]  INT         NOT NULL,
    [ACTION_TIME] ROWVERSION  NULL,
    [ACTION_NAME] NCHAR (100) NULL,
    [DESCRIPTION] NCHAR (100) NULL,
    [USER_ID]     INT         NOT NULL,
    CONSTRAINT [PK_RC_ACTION_HISTORY] PRIMARY KEY CLUSTERED ([ID] ASC)
);

