CREATE TABLE [dbo].[RC_ACCOUNT_LEVEL] (
    [ACCOUNT_LEVEL_ID] INT IDENTITY (1, 1) NOT NULL,
	[LEVEL_NAME] NCHAR (60) NOT NULL,
    CONSTRAINT [PK_RC_ACCOUNT_LEVEL] PRIMARY KEY CLUSTERED ([ACCOUNT_LEVEL_ID] ASC),
);