CREATE TABLE [dbo].[RC_MENU_MODIFIER_GROUP] (
    [MODIFIER_GROUP_ID] BIGINT         IDENTITY (1, 1) NOT NULL,
    [ACCOUNT_ID]        BIGINT         NOT NULL,
    [NAME]              NCHAR (100) NOT NULL,
    [ENABLED]           SMALLINT    NULL,
    [EXCLUSIVED]        SMALLINT    NULL,
    [REQUIRED]          SMALLINT    NULL,
    [MODIFIED_TIME]     ROWVERSION  NULL,
    [MODIFIED_BY]       INT         NULL,
    CONSTRAINT [PK_RC_MENU_MODIFIER_GROUP] PRIMARY KEY CLUSTERED ([MODIFIER_GROUP_ID] ASC),
	CONSTRAINT [FK_RC_MENU_MODIFIER_GROUP_RC_ACCOUNTS] FOREIGN KEY ([ACCOUNT_ID]) REFERENCES [dbo].[RC_ACCOUNTS] ([ACCOUNT_ID]),
);