CREATE TABLE [dbo].[RC_MENU_GROUP] (
    [GROUP_ID]      BIGINT         IDENTITY (1, 1) NOT NULL,
    [ACCOUNT_ID]    BIGINT         NOT NULL,
    [CATEGORY_ID]   BIGINT         NOT NULL,
    [NAME]          NCHAR (100) NOT NULL,
    [VISIBLE]       SMALLINT    NOT NULL,
    [MODIFIED_TIME] ROWVERSION  NOT NULL,
    [MODIFIED_BY]   BIGINT         NULL,
    CONSTRAINT [PK_RC_MENU_GROUP] PRIMARY KEY CLUSTERED ([GROUP_ID] ASC),
	CONSTRAINT [FK_RC_MENU_GROUP_RC_ACCOUNTS] FOREIGN KEY ([ACCOUNT_ID]) REFERENCES [dbo].[RC_ACCOUNTS] ([ACCOUNT_ID]),
	CONSTRAINT [FK_RC_MENU_GROUP_RC_MENU_CATEGORY] FOREIGN KEY ([CATEGORY_ID]) REFERENCES [dbo].[RC_MENU_CATEGORY] ([CATEGORY_ID]),
);