CREATE TABLE [dbo].[RC_MENU_CATEGORY] (
    [CATEGORY_ID]   BIGINT         IDENTITY (1, 1) NOT NULL,
    [ACCOUNT_ID]    BIGINT         NOT NULL,
    [NAME]          NCHAR (100) NOT NULL,
    [VISIBLE]       SMALLINT    NOT NULL,
    [MODIFIED_TIME] ROWVERSION  NOT NULL,
    [MODIFIED_BY]   BIGINT      NULL,
    CONSTRAINT [PK_RC_MENU_CATEGORY] PRIMARY KEY CLUSTERED ([CATEGORY_ID] ASC),
	CONSTRAINT [FK_RC_MENU_CATEGORY_RC_ACCOUNTS] FOREIGN KEY ([ACCOUNT_ID]) REFERENCES [dbo].[RC_ACCOUNTS] ([ACCOUNT_ID])
);