CREATE TABLE [dbo].[RC_MENU_ITEM] (
    [ITEM_ID]       BIGINT             IDENTITY (1, 1) NOT NULL,
    [ACCOUNT_ID]    BIGINT             NOT NULL,
    [GROUP_ID]      BIGINT             NOT NULL,
    [PRICE]         DECIMAL (18, 2) NOT NULL,
    [VISIBLE]       SMALLINT        NOT NULL,
    [MODIFIED_TIME] ROWVERSION      NOT NULL,
    [MODIFIED_BY]   INT             NULL,
    CONSTRAINT [PK_RC_MENU_ITEM] PRIMARY KEY CLUSTERED ([ITEM_ID] ASC),
	CONSTRAINT [FK_RC_MENU_ITEM_RC_ACCOUNTS] FOREIGN KEY ([ACCOUNT_ID]) REFERENCES [dbo].[RC_ACCOUNTS] ([ACCOUNT_ID]),
	CONSTRAINT [FK_RC_MENU_ITEM_RC_MENU_GROUP] FOREIGN KEY ([GROUP_ID]) REFERENCES [dbo].[RC_MENU_GROUP] ([GROUP_ID]),
);