CREATE TABLE [dbo].[RC_MENU_MODIFER] (
    [MODIFIER_ID]   BIGINT             IDENTITY (1, 1) NOT NULL,
    [ACCOUNT_ID]    BIGINT             NOT NULL,
    [NAME]          NCHAR (100)     NOT NULL,
    [PRICE]         DECIMAL (18, 2) NOT NULL,
    [EXTRA_PRICE]   DECIMAL (18, 2) NOT NULL,
    [ENABLE]        SMALLINT        NOT NULL,
    [GROUP_ID]      INT             NOT NULL,
    [TAX_ID]        INT             NOT NULL,
    [MODIFIED_TIME] ROWVERSION      NOT NULL,
    [MODIFIER_BY]   INT             NULL,
    CONSTRAINT [PK_RC_MENU_MODIFER] PRIMARY KEY CLUSTERED ([MODIFIER_ID] ASC),
	CONSTRAINT [FK_RC_MENU_MODIFER_RC_ACCOUNTS] FOREIGN KEY ([ACCOUNT_ID]) REFERENCES [dbo].[RC_ACCOUNTS] ([ACCOUNT_ID]),
);

