CREATE TABLE [dbo].[RC_PRINTER_CONFIG] (
    [PRINTER_ID]    BIGINT         IDENTITY (1, 1) NOT NULL,
    [ACCOUNT_ID]    BIGINT         NOT NULL,
    [NAME]          NCHAR (100) NOT NULL,
    [TYPE]          INT         NOT NULL,
    [MODIFIED_TIME] ROWVERSION  NOT NULL,
    [MODIFIED_BY]   BIGINT      NULL,
    CONSTRAINT [PK_RC_PRINTER_CONFIG] PRIMARY KEY CLUSTERED ([PRINTER_ID] ASC),
	CONSTRAINT [FK_RC_PRINTER_CONFIG_RC_ACCOUNTS] FOREIGN KEY ([ACCOUNT_ID]) REFERENCES [dbo].[RC_ACCOUNTS] ([ACCOUNT_ID])
);

