CREATE TABLE [dbo].[RC_RESTO_PAYMENT_MOTHOD] (
    [METHOD_ID]  BIGINT      NOT NULL,
    [ACCOUNT_ID] BIGINT      NOT NULL,
    [ENABLED]    SMALLINT NOT NULL,
    CONSTRAINT [PK_RC_RESTO_PAYMENT_MOTHOD] PRIMARY KEY CLUSTERED ([METHOD_ID] ASC, [ACCOUNT_ID] ASC),
	CONSTRAINT [FK_RC_RESTO_PAYMENT_MOTHOD_RC_ACCOUNTS] FOREIGN KEY ([ACCOUNT_ID]) REFERENCES [dbo].[RC_ACCOUNTS] ([ACCOUNT_ID]),
	CONSTRAINT [FK_RC_RESTO_PAYMENT_MOTHOD_RC_PAYMENT_METHOD] FOREIGN KEY ([METHOD_ID]) REFERENCES [dbo].[RC_PAYMENT_METHOD] ([ID]),
);