CREATE TABLE [dbo].[RC_SHIFT] (
    [SHIFT_ID]      BIGINT         NOT NULL,
    [ACCOUNT_ID]    BIGINT         NOT NULL,
    [NAME]          NCHAR (100) NULL,
    [START_TIME]    BIGINT      NOT NULL,
    [SHIFT_LEN]     BIGINT      NULL,
    [MODIFIED_TIME] ROWVERSION  NOT NULL,
    [MODIFIED_BY]   BIGINT      NULL,
    CONSTRAINT [PK_RC_SHIFT] PRIMARY KEY CLUSTERED ([SHIFT_ID] ASC),
	CONSTRAINT [FK_RC_SHIFT_RC_ACCOUNTS] FOREIGN KEY ([ACCOUNT_ID]) REFERENCES [dbo].[RC_ACCOUNTS] ([ACCOUNT_ID])
);