CREATE TABLE [dbo].[RC_TAX] (
    [TAX_ID]        BIGINT             NOT NULL,
    [ACCOUNT_ID]    BIGINT             NULL,
    [NAME]          NCHAR (100)     NOT NULL,
    [RATE]          DECIMAL (18, 2) NULL,
    [MODIFIED_TIME] ROWVERSION      NULL,
    [MODIFIED_BY]   INT             NULL,
    CONSTRAINT [PK_RC_TAX] PRIMARY KEY CLUSTERED ([TAX_ID] ASC),
	CONSTRAINT [FK_RC_TAX_RC_ACCOUNTS] FOREIGN KEY ([ACCOUNT_ID]) REFERENCES [dbo].[RC_ACCOUNTS] ([ACCOUNT_ID]),
);