CREATE TABLE [dbo].[RC_TICKET_MODIFIER] (
    [TICKET_ID]                  BIGINT IDENTITY (1, 1) NOT NULL,
    [ITEM_ID]                    BIGINT             NOT NULL,
    [GROUP_ID]                   BIGINT             NOT NULL,
    [ITEM_COUNT]                 INT             NOT NULL,
    [MODIFIER_NAME]              NCHAR (100)     NOT NULL,
    [MODIFIER_PRICE]             DECIMAL (18, 2) NOT NULL,
    [EXTRA_PRICE]                DECIMAL (18, 2) NULL,
    [MODIFIER_TYPE]              INT             NULL,
    [PRINT_TO_KITCHEN]           SMALLINT        NULL,
    [MODIFIERGROUP_ID]           INT             NULL,
    [TICKETITEMMODIFIERGROUP_ID] INT             NULL,
    [ITEM_ORDER]                 INT             NULL,
    [MODIFIED_TIME]              ROWVERSION      NOT NULL,
    [MODIFIED_BY]                INT             NULL,
    CONSTRAINT [PK_RC_TICKET_MODIFIER] PRIMARY KEY CLUSTERED ([TICKET_ID] ASC),
	CONSTRAINT [FK_RC_TICKET_MODIFIER_RC_TICKETS] FOREIGN KEY ([TICKET_ID]) REFERENCES [dbo].[RC_TICKETS] ([TICKET_ID]),
	CONSTRAINT [FK_RC_TICKET_MODIFIER_RC_MENU_ITEM] FOREIGN KEY ([ITEM_ID]) REFERENCES [dbo].[RC_MENU_ITEM] ([ITEM_ID]),
);

