CREATE TABLE [dbo].[RC_USERS] (
    [USER_ID]       BIGINT  IDENTITY (1, 1) NOT NULL,
    [LOGIN_NAME]    NCHAR (60) NOT NULL,
    [ACCOUNT_ID]    BIGINT     NOT NULL,
    [SHIFT_ID]      BIGINT     NULL,
    [FIRST_NAME]    NCHAR (30) NULL,
    [LAST_NAME]     NCHAR (30) NULL,
    [PASSWORD]      NVARCHAR (50) NOT NULL,
    [MODIFIED_TIME] ROWVERSION NOT NULL,
    [MODIFIED_BY]   BIGINT     NULL,
    CONSTRAINT [PK_RC_USERS] PRIMARY KEY CLUSTERED ([USER_ID] ASC),
	CONSTRAINT [FK_RC_USERS_RC_ACCOUNTS] FOREIGN KEY ([ACCOUNT_ID]) REFERENCES [dbo].[RC_ACCOUNTS] ([ACCOUNT_ID]),
	CONSTRAINT [FK_RC_USERS_RC_SHIFT] FOREIGN KEY ([SHIFT_ID]) REFERENCES [dbo].[RC_SHIFT] ([SHIFT_ID]),
);